spring:
  profiles:
    active: secret
server:

  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  port: 8000

logging:
  level:
    org:
      hibernate:
        SQL: DEBUG
        type:
          descriptor:
            sql:
              BasicBinder: TRACE

springfox:
  documentation:
    swagger:
      use-model-v3: false
