spring:
  profiles:
    active: secret

  jpa:
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    open-in-view: false
    hibernate:
      ddl-auto: create
      show_sql: true
      format_sql: true
      use_sql_comments: true

  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

logging:
  level:
    org:
      hibernate:
        SQL: DEBUG
        type:
          descriptor:
            sql:
              BasicBinder: TRACE

springfox:
  documentation:
    swagger:
      use-model-v3: false


